#!/bin/sh
#
# Start/stop nginx
#

PIDFILE=/run/nginx.pid

case "$1" in
  start)
	echo "Starting nginx..."
	start-stop-daemon -S -x nginx
	;;
  stop)
	echo -n "Stopping nginx..."
	start-stop-daemon -K -o -p $PIDFILE
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
